#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from coolc.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "coolc.y"

/*
*	Parser specification 
*/
#include	<stdio.h>
#include	<stdlib.h>
#include	<string.h>
#include	"symbol.h"
#include	"nodes.h"
#include	"codegen.h"
#include	"inter.h"

int		lineno	= 1;
extern int	yylex();	
extern char	*yytext;

int initial_pc;
struct ClassList *classlist;
/* the code and data segments */
TAC_ENTRY code[MAX_CODE];
DATA_ENTRY data[MAX_DATA];
int error=0;

void yyerror(char *s)
{
	fprintf(stderr,"Syntax error on line #%d: %s\n",lineno,s);
	fprintf(stderr,"Last token was \"%s\"\n",yytext);
	exit(1);
}


#line 33 "coolc.y"
typedef union{
	int		iValue;
	char		*cValue;
	struct node	*nptr;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	LPAREN	258
#define	RPAREN	259
#define	LBRACE	260
#define	RBRACE	261
#define	EQUAL	262
#define	NUMBER	263
#define	SEMICOLON	264
#define	DOTS	265
#define	COLON	266
#define	PLUS	267
#define	MINUS	268
#define	ASSIGN	269
#define	CLASS	270
#define	IS	271
#define	END	272
#define	TYPEID	273
#define	ID	274
#define	IF	275
#define	THEN	276
#define	ELSE	277
#define	FI	278
#define	WHILE	279
#define	LOOP	280
#define	POOL	281
#define	NOT	282
#define	BBEGIN	283
#define	DOT	284
#define	TRUE	285
#define	FALSE	286
#define	PRINT	287
#define	STRING	288


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int LPAREN;
static const int RPAREN;
static const int LBRACE;
static const int RBRACE;
static const int EQUAL;
static const int NUMBER;
static const int SEMICOLON;
static const int DOTS;
static const int COLON;
static const int PLUS;
static const int MINUS;
static const int ASSIGN;
static const int CLASS;
static const int IS;
static const int END;
static const int TYPEID;
static const int ID;
static const int IF;
static const int THEN;
static const int ELSE;
static const int FI;
static const int WHILE;
static const int LOOP;
static const int POOL;
static const int NOT;
static const int BBEGIN;
static const int DOT;
static const int TRUE;
static const int FALSE;
static const int PRINT;
static const int STRING;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,LPAREN=258
	,RPAREN=259
	,LBRACE=260
	,RBRACE=261
	,EQUAL=262
	,NUMBER=263
	,SEMICOLON=264
	,DOTS=265
	,COLON=266
	,PLUS=267
	,MINUS=268
	,ASSIGN=269
	,CLASS=270
	,IS=271
	,END=272
	,TYPEID=273
	,ID=274
	,IF=275
	,THEN=276
	,ELSE=277
	,FI=278
	,WHILE=279
	,LOOP=280
	,POOL=281
	,NOT=282
	,BBEGIN=283
	,DOT=284
	,TRUE=285
	,FALSE=286
	,PRINT=287
	,STRING=288


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::LPAREN=258;
const int YY_parse_CLASS::RPAREN=259;
const int YY_parse_CLASS::LBRACE=260;
const int YY_parse_CLASS::RBRACE=261;
const int YY_parse_CLASS::EQUAL=262;
const int YY_parse_CLASS::NUMBER=263;
const int YY_parse_CLASS::SEMICOLON=264;
const int YY_parse_CLASS::DOTS=265;
const int YY_parse_CLASS::COLON=266;
const int YY_parse_CLASS::PLUS=267;
const int YY_parse_CLASS::MINUS=268;
const int YY_parse_CLASS::ASSIGN=269;
const int YY_parse_CLASS::CLASS=270;
const int YY_parse_CLASS::IS=271;
const int YY_parse_CLASS::END=272;
const int YY_parse_CLASS::TYPEID=273;
const int YY_parse_CLASS::ID=274;
const int YY_parse_CLASS::IF=275;
const int YY_parse_CLASS::THEN=276;
const int YY_parse_CLASS::ELSE=277;
const int YY_parse_CLASS::FI=278;
const int YY_parse_CLASS::WHILE=279;
const int YY_parse_CLASS::LOOP=280;
const int YY_parse_CLASS::POOL=281;
const int YY_parse_CLASS::NOT=282;
const int YY_parse_CLASS::BBEGIN=283;
const int YY_parse_CLASS::DOT=284;
const int YY_parse_CLASS::TRUE=285;
const int YY_parse_CLASS::FALSE=286;
const int YY_parse_CLASS::PRINT=287;
const int YY_parse_CLASS::STRING=288;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		70
#define	YYFLAG		-32768
#define	YYNTBASE	34

#define YYTRANSLATE(x) ((unsigned)(x) <= 288 ? yytranslate[x] : 45)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     5,     9,    12,    16,    20,    21,    32,    36,
    42,    45,    49,    50,    54,    58,    65,    73,    79,    83,
    86,    88,    90,    92,    94,    97,   100,   104,   105,   108
};

static const short yyrhs[] = {    35,
     0,    36,     9,     0,    35,    36,     9,     0,    37,    17,
     0,    15,    18,    16,     0,    37,    38,     9,     0,     0,
    19,     3,    40,     4,    10,    18,    16,    39,    44,    17,
     0,    19,    10,    18,     0,    19,    10,    18,    14,    42,
     0,    40,    41,     0,    40,    41,    11,     0,     0,    19,
    10,    18,     0,    19,    14,    42,     0,    19,    29,    19,
     3,    43,     4,     0,    20,    42,    21,    42,    22,    42,
    23,     0,    24,    42,    25,    42,    26,     0,    28,    44,
    17,     0,    27,    42,     0,    19,     0,     8,     0,    30,
     0,    31,     0,    32,    33,     0,    43,    42,     0,    43,
    42,    11,     0,     0,    42,     9,     0,    44,    42,     9,
     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    50,    54,    59,    67,    74,    86,    97,   115,   151,   162,
   175,   178,   181,   186,   192,   206,   232,   243,   252,   256,
   270,   276,   280,   284,   288,   309,   310,   311,   314,   317
};

static const char * const yytname[] = {   "$","error","$illegal.","LPAREN","RPAREN",
"LBRACE","RBRACE","EQUAL","NUMBER","SEMICOLON","DOTS","COLON","PLUS","MINUS",
"ASSIGN","CLASS","IS","END","TYPEID","ID","IF","THEN","ELSE","FI","WHILE","LOOP",
"POOL","NOT","BBEGIN","DOT","TRUE","FALSE","PRINT","STRING","program","c_list",
"class","feature_list","feature","@1","formal_list","formal","expr","param_list",
"expr_list",""
};
#endif

static const short yyr1[] = {     0,
    34,    35,    35,    36,    37,    37,    39,    38,    38,    38,
    40,    40,    40,    41,    42,    42,    42,    42,    42,    42,
    42,    42,    42,    42,    42,    43,    43,    43,    44,    44
};

static const short yyr2[] = {     0,
     1,     2,     3,     2,     3,     3,     0,    10,     3,     5,
     2,     3,     0,     3,     3,     6,     7,     5,     3,     2,
     1,     1,     1,     1,     2,     2,     3,     0,     2,     3
};

static const short yydefact[] = {     0,
     0,     1,     0,     0,     0,     0,     2,     4,     0,     0,
     5,     3,    13,     0,     6,     0,     9,     0,     0,    11,
     0,     0,     0,    12,    22,    21,     0,     0,     0,     0,
    23,    24,     0,    10,     0,    14,     0,     0,     0,     0,
    20,     0,     0,    25,     7,    15,     0,     0,     0,    29,
    19,     0,     0,    28,     0,     0,    30,     0,     0,     0,
    18,     8,    16,    26,     0,    27,    17,     0,     0,     0
};

static const short yydefgoto[] = {    68,
     2,     3,     4,    10,    53,    16,    20,    42,    59,    43
};

static const short yypact[] = {   -14,
   -13,   -14,     0,    -7,    -3,     5,-32768,-32768,     1,     6,
-32768,-32768,-32768,     3,-32768,    -2,     9,    15,    19,     8,
    64,    12,    13,-32768,-32768,   -11,    64,    64,    64,    64,
-32768,-32768,    -1,-32768,    10,-32768,    64,    14,    21,    20,
-32768,    25,    33,-32768,-32768,-32768,    46,    64,    64,-32768,
-32768,    42,    64,-32768,    32,    29,-32768,    50,    16,    64,
-32768,-32768,-32768,    45,    36,-32768,-32768,    62,    66,-32768
};

static const short yypgoto[] = {-32768,
-32768,    69,-32768,-32768,-32768,-32768,-32768,   -21,-32768,    22
};


#define	YYLAST		96


static const short yytable[] = {    34,
     1,    18,    37,    13,     5,    39,    40,    41,     7,     8,
    14,     9,    11,    12,    15,    46,    19,    38,    24,    63,
    17,    52,    21,    25,    22,    45,    55,    56,    23,    35,
    36,    44,    47,    50,    26,    27,    52,    64,    65,    28,
    25,    48,    29,    30,    49,    31,    32,    33,    54,    51,
    57,    26,    27,    60,    61,    66,    28,    25,    67,    29,
    30,    69,    31,    32,    33,    70,    62,     0,    26,    27,
     6,    25,     0,    28,    58,     0,    29,    30,     0,    31,
    32,    33,    26,    27,     0,     0,     0,    28,     0,     0,
    29,    30,     0,    31,    32,    33
};

static const short yycheck[] = {    21,
    15,     4,    14,     3,    18,    27,    28,    29,     9,    17,
    10,    19,    16,     9,     9,    37,    19,    29,    11,     4,
    18,    43,    14,     8,    10,    16,    48,    49,    10,    18,
    18,    33,    19,     9,    19,    20,    58,    59,    60,    24,
     8,    21,    27,    28,    25,    30,    31,    32,     3,    17,
     9,    19,    20,    22,    26,    11,    24,     8,    23,    27,
    28,     0,    30,    31,    32,     0,    17,    -1,    19,    20,
     2,     8,    -1,    24,    53,    -1,    27,    28,    -1,    30,
    31,    32,    19,    20,    -1,    -1,    -1,    24,    -1,    -1,
    27,    28,    -1,    30,    31,    32
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 50 "coolc.y"
{ 
		;
    break;}
case 2:
#line 54 "coolc.y"
{ 
			if (yyvsp[-1].nptr->type==ERROR) {
				error=1;
			}
		;
    break;}
case 3:
#line 59 "coolc.y"
{
			/* Our tree finished here */
			if (yyvsp[-1].nptr->type==ERROR) {
				error=1;
			}
		;
    break;}
case 4:
#line 67 "coolc.y"
{ 
			st_exitclass();
			yyval.nptr=mk_node_oper("CLASS",yyvsp[-1].nptr,NULL,NULL);
			yyval.nptr->type=yyvsp[-1].nptr->type;
		;
    break;}
case 5:
#line 74 "coolc.y"
{
			int st_idx;
			/* Add the class. Error if already present */
			st_idx=st_update(yyvsp[-1].cValue,TYPE_CLASS,0,0);
			/* Create the current environment */
			st_enterclass();
			yyval.nptr=mk_node_oper("FLIST-END",NULL,NULL,NULL);
			if (st_idx==ERROR) {
				printf("Error(%d): Redefinition of Class %s\n",lineno-1,(char*)yyvsp[-1].cValue);
				yyval.nptr->type=ERROR;
			}
		;
    break;}
case 6:
#line 86 "coolc.y"
{
			yyval.nptr=mk_node_oper("FLIST",yyvsp[-2].nptr,yyvsp[-1].nptr,NULL);
			if ((yyvsp[-1].nptr->type)==ERROR) {
				yyval.nptr->type=ERROR;
			}
			if ((yyvsp[-2].nptr->type)==ERROR) {
				yyval.nptr->type=ERROR;
			}
		;
    break;}
case 7:
#line 97 "coolc.y"
{
			int lpos;
			/* Emit the method beginning and mark it
			   into the symbol table */
			lpos=code_emit(C_MBEGIN,0,0,0);

			/* Check that it's not already defined */
			if (st_update(yyvsp[-6].cValue,TYPE_METHOD,st_lookup(yyvsp[-1].cValue,TYPE_CLASS),lpos)==ERROR) {
				printf("Error(%d): Redefinition of Method %s::%s\n",lineno-1,st_getname(cl_current()),(char*)yyvsp[-6].cValue);
				error=1;
			}

			/* Is the main() method of Main? If so mark the initial PC */
			if ((strcmp(yyvsp[-6].cValue,"main")==0) && (strcmp(st_getname(cl_current()),"Main")==0)) {
				initial_pc=lpos;
/*				printf("Found Main::main()\n"); */
			}
			
		 ;
    break;}
case 8:
#line 115 "coolc.y"
{
			/* Node with Name and parameters tree and code */
			yyval.nptr=mk_node_oper(yyvsp[-9].cValue,yyvsp[-7].nptr,yyvsp[-1].nptr,NULL);

/* Test code: prints out the parameters and their types 
			{	struct node *p=$3;
				printf("Method %s has:\n",$1);
				while(p) {	
					if (p->op2) printf("  argument %d of type %d\n",p->op2->st_pnt,p->op2->type);
					p=p->op1;
				}
				printf("\n");
			}
*/
			if (yyvsp[-1].nptr->type==ERROR) {
				yyval.nptr->type=ERROR;
			} else {
				/*
				   Method type checking:
				   Last expression in the method code MUST have the
				   same type as method definition. To complete we
				   should do also check on parameters type and number (not implemented)
				*/
				if (st_lookup(yyvsp[-4].cValue,TYPE_CLASS)==yyvsp[-1].nptr->type) {
					yyval.nptr->type=yyvsp[-1].nptr->type;
				} else {
					printf("Error(%d): %s::%s returns different type from declaration\n",lineno-1,st_getname(cl_current()),yyvsp[-9].cValue);
					yyval.nptr->type=ERROR;
				}
			}

			/* Emit end of method */
			code_emit(C_RETURN,0,0,0);
			code_emit(C_MEND,0,0,0);

		;
    break;}
case 9:
#line 151 "coolc.y"
{
			/* Add the attribute in the symbol table (and consequently to class definition) 
			   Just notify an error if already present.
			*/
			yyval.nptr=mk_node_ide(st_gettype(st_lookup(yyvsp[0].cValue,TYPE_CLASS)),st_lookup(yyvsp[-2].cValue,TYPE_ATTRIB));
			if (st_update(yyvsp[-2].cValue,TYPE_ATTRIB,st_lookup(yyvsp[0].cValue,TYPE_CLASS),0)==ERROR) {
				printf("Error(%d): Redefinition of Attribute %s::%s\n",lineno-1,st_getname(cl_current()),(char*)yyvsp[-2].cValue);
				yyval.nptr->type=ERROR;
			}

		;
    break;}
case 10:
#line 162 "coolc.y"
{
			/* Add the attribute in the symbol table (and consequently to class definition) 
			   Just notify an error if already present.
			*/
			yyval.nptr=mk_node_ide(st_gettype(st_lookup(yyvsp[-2].cValue,TYPE_CLASS)),st_lookup(yyvsp[-4].cValue,TYPE_ATTRIB));
			if (st_update(yyvsp[-4].cValue,TYPE_ATTRIB,st_lookup(yyvsp[-2].cValue,TYPE_CLASS),0)==ERROR) {
				printf("Error(%d): Redefinition of Attribute %s::%s\n",lineno-1,st_getname(cl_current()),(char*)yyvsp[-4].cValue);
				yyval.nptr->type=ERROR;
			}

		;
    break;}
case 11:
#line 175 "coolc.y"
{
			yyval.nptr=mk_node_oper("Formal List",yyvsp[-1].nptr,yyvsp[0].nptr,NULL);
		;
    break;}
case 12:
#line 178 "coolc.y"
{
			yyval.nptr=mk_node_oper("Formal List",yyvsp[-2].nptr,yyvsp[-1].nptr,NULL);
		;
    break;}
case 13:
#line 181 "coolc.y"
{
			yyval.nptr=NULL;
		;
    break;}
case 14:
#line 186 "coolc.y"
{
			st_update(yyvsp[-2].cValue,TYPE_ARG,st_lookup(yyvsp[0].cValue,TYPE_CLASS),0);
			yyval.nptr=mk_node_ide(st_gettype(st_lookup(yyvsp[0].cValue,TYPE_CLASS)),st_lookup(yyvsp[-2].cValue,TYPE_ARG));
		;
    break;}
case 15:
#line 192 "coolc.y"
{ 
			yyval.nptr=mk_node_ide(st_gettype(st_lookup(yyvsp[-2].cValue,TYPE_ATTRIB)),st_lookup(yyvsp[-2].cValue,TYPE_CLASS));
			if (st_lookup(yyvsp[-2].cValue,TYPE_ATTRIB)==ERROR) {
				printf("Error(%d): Undeclared variable %s used\n",lineno-1,yyvsp[-2].cValue);
				yyval.nptr->type=ERROR;
			} else {
				if (yyval.nptr->type == yyvsp[0].nptr->type) {
					yyval.nptr->value=yyvsp[0].nptr->value;
				} else {
					printf("Error(%d): Incompatible variable assignment\n",lineno-1);
					yyval.nptr->type=ERROR;
				}
			}
		;
    break;}
case 16:
#line 206 "coolc.y"
{
			int st_pointer;
			/* Dispatch - object, method, params */
			yyval.nptr=mk_node_oper("PROCEDURE CALL",yyvsp[-1].nptr,NULL,NULL);
			st_pointer=st_lookup(yyvsp[-5].cValue,TYPE_ATTRIB);

			/* First check if the object is present in the running scope */
			if (st_pointer == -1) {
				printf("Error(%d): Variable %s not found\n",lineno-1,yyvsp[-5].cValue);
				yyval.nptr->type=ERROR;
			} else {
				/* see in such an object there is such a method */
				int m_id=cl_inclass(yyvsp[-3].cValue,TYPE_METHOD,st_gettype(st_pointer));
				if (m_id == ERROR) {
					printf("Error(%d): Method %s not in class %s\n",lineno-1,yyvsp[-3].cValue,yyvsp[-5].cValue);
					yyval.nptr->type=ERROR;
				} else {
					/* Everything is ok, so emit the call to the code and
					   all the other needed stuff */
					code_emit(C_CALL,st_getoff(m_id),0,0);
		
					/* used for type-checking of the program (incomplete !!!) */
					yyval.nptr->type=st_gettype(m_id);
				}
			}
		;
    break;}
case 17:
#line 232 "coolc.y"
{ 
			yyval.nptr=mk_node_oper("IF THEN ELSE",yyvsp[-5].nptr,yyvsp[-3].nptr,yyvsp[-1].nptr);
			if (yyvsp[-5].nptr->type!=st_lookup("Bool",TYPE_CLASS)) {
				printf("Error(%d): IF condition is not a boolean\n",lineno-1);
				yyval.nptr->type=ERROR;
			} else {
				/* not dealing with supertipes, so just assume they are equal */
				yyval.nptr->type=yyvsp[-3].nptr->type;
			}

		;
    break;}
case 18:
#line 243 "coolc.y"
{ 
			yyval.nptr=mk_node_oper("WHILE LOOP",yyvsp[-3].nptr,yyvsp[-1].nptr,NULL);
			if (yyvsp[-3].nptr->type!=st_lookup("Bool",TYPE_CLASS)) {
				printf("Error(%d): WHILE condition is not a boolean\n",lineno-1);
				yyval.nptr->type=ERROR;
			} else {
				yyval.nptr->type=yyvsp[-1].nptr->type;
			}
		;
    break;}
case 19:
#line 252 "coolc.y"
{
			yyval.nptr=mk_node_oper("BLOCK",yyvsp[-1].nptr,NULL,NULL);
			yyval.nptr->type=yyvsp[-1].nptr->type;
		;
    break;}
case 20:
#line 256 "coolc.y"
{ 
			yyval.nptr=mk_node_oper("NOT",yyvsp[0].nptr,NULL,NULL);
			if (yyvsp[0].nptr->type == ERROR) {
				yyval.nptr->type=ERROR;
			} else {
				if (yyvsp[0].nptr->type == st_lookup("Bool",TYPE_CLASS)) {
					yyval.nptr->value=!(yyvsp[0].nptr->value);
					yyval.nptr->type=st_lookup("Bool",TYPE_CLASS);
				} else {
					printf("Error(%d): NOT applied to a non boolean\n",lineno-1);
					yyval.nptr->type=ERROR;
				}
			}
		;
    break;}
case 21:
#line 270 "coolc.y"
{ 
			if (st_lookup(yyvsp[0].cValue,TYPE_ATTRIB)==-1) {
				printf("Error(%d): Symbol %s undeclared before\n",lineno-1,yyvsp[0].cValue);
			}
			yyval.nptr=mk_node_ide(st_gettype(st_lookup(yyvsp[0].cValue,TYPE_ATTRIB)),st_lookup(yyvsp[0].cValue,TYPE_ATTRIB));
		;
    break;}
case 22:
#line 276 "coolc.y"
{ 
			yyval.nptr=mk_node_value(st_lookup("Int",TYPE_CLASS),yyvsp[0].iValue);
			code_emit(C_CONST,yyvsp[0].iValue,0,0);
		;
    break;}
case 23:
#line 280 "coolc.y"
{ 
			yyval.nptr=mk_node_value(st_lookup("Bool",TYPE_CLASS),1);
			code_emit(C_CONST,1,0,0);
		;
    break;}
case 24:
#line 284 "coolc.y"
{
			yyval.nptr=mk_node_value(st_lookup("Bool",TYPE_CLASS),0);
			code_emit(C_CONST,0,0,0);
		;
    break;}
case 25:
#line 288 "coolc.y"
{
			/* first we insert the string in the symbol table and then
			   emit the code with the reference to it (not reference to
			   symbol table but to our data segment  */
			int str_mof;
			int st_nr=st_lookup(yyvsp[0].cValue,TYPE_STRING);
			if (st_nr==-1) {
				/* New string, must first insert  */
				str_mof=code_data(yyvsp[0].cValue);
				st_nr=st_update(yyvsp[0].cValue,TYPE_STRING,-1,str_mof);
			}
			/* Get offset in data segment (may be optimized) */
			str_mof=st_getoff(st_nr);
			code_emit(C_PRINT,str_mof,0,0);
			/* print is NOT a Cool standard expression. Let's assume
			   it's type is *always* Int and the value is the string
			   lenght excluding the quotes */
			yyval.nptr=mk_node_value(st_lookup("Int",TYPE_CLASS),strlen(yyvsp[0].cValue)-2);
		;
    break;}
case 26:
#line 309 "coolc.y"
{;
    break;}
case 27:
#line 310 "coolc.y"
{;
    break;}
case 28:
#line 311 "coolc.y"
{;
    break;}
case 29:
#line 314 "coolc.y"
{ 
			yyval.nptr=yyvsp[-1].nptr;
		;
    break;}
case 30:
#line 317 "coolc.y"
{
			/* the type of the expression list is the type of
			   the last expression or ERROR */
			yyval.nptr=mk_node_oper("EXPRLIST",yyvsp[-2].nptr,yyvsp[-1].nptr,NULL);
			if (yyvsp[-2].nptr->type!=ERROR) {
				yyval.nptr->type=yyvsp[-1].nptr->type;
			} else {
				yyval.nptr->type=ERROR;
			}
		;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 329 "coolc.y"


int main(int argc,char *argv[])
{
	classlist=NULL;
	
	/* clean up the symbol table */
	st_init();
	
	/* add the very basic types */
	st_update("Int",TYPE_CLASS,0,0);
	st_update("Bool",TYPE_CLASS,0,0);

	yyparse();

	if (error!=0) {
		printf("Errors during compilation, aborting execution\n");
		return -1;
	}

	/* at the end dump:
		the symbol table
		the classlist info
		the generated chunks of code
	*/
	st_dumpall();
	cl_showall();
	code_showall();

	if (initial_pc==0) {
		printf("main() in object Main not found, trying to execute from PC=0\n");
	} else {
		printf("Main::main() found at PC %d, executing\n",initial_pc);
	}

	printf("\nCleaning up internal structures:");
	printf(" Symbol table,");
	st_kill();
	printf(" Classlist\n");
	cl_kill();

	printf("\nExecuting the Compiler... The result obtained\n\n");
	inter_exec(initial_pc,code,data);

	return 0;
}
